name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: write
  id-token: write
jobs:
  lint:
    name: Lint
    uses: gofor-little/github-actions/.github/workflows/golang-lint.yaml@main
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      TEST_SMS_RECIPIENTS: ${{ secrets.TEST_SMS_RECIPIENTS }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::320045747480:role/github-actions
      - name: Run Tests
        run: go test -v -race ./...
  bump-tag:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - lint
      - test
    name: Bump Tag
    uses: gofor-little/github-actions/.github/workflows/bump-tag.yaml@main
  release:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs:
      - bump-tag
    name: Release
    uses: gofor-little/github-actions/.github/workflows/github-release.yaml@main
    with:
      tag: ${{ needs.bump-tag.outputs.bumped-tag }}
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
